### ISSUE TITLE
Using grunticon as a SVG fallback

### ISSUE THREAD

**Issue by laurendorman** [sparkbox/apprentice-at#146]

**Comment by kaseybon** [comment]
I played around with this method and it really does more harm than good. The picture element has less support than svg so it will show a png for browsers that actually support svg.

**Comment by danrosenthal** [comment]
I had the same issue. Maybe best just to stick with PNG for these unless we want to use JS and modernizr to fill in the src field.

**Comment by kaseybon** [comment]
I talked to Zastrow about about optimizing svgs and providing fallbacks and he mentioned using grunticon. I think I want to give that a try or there is also using modernizr which is already implemented. If we go the modernizr route I have a code snippet that will swap out the file extension as needed but it uses jQuery and I don't want to use it if that's the only thing we are going to use jQuery for.

**Comment by kaseybon** [comment]
Used the object for fallbacks instead.
