### ISSUE TITLE
Firefox: Drop the width on the radio buttons

### ISSUE THREAD

**Issue by kaseybon** [sparkbox/apprentice-at#185]
The 1.5rem width is causing the radio buttons to look pixilated. If we lose the width they look fine.

**Comment by laurendorman** [comment]
Only problem with removing the width on these is that we deflate button for Chrome/Safari.
![Uploading Screen Shot 2015-06-15 at 11.05.58 AM.png…]()

**Comment by kaseybon** [comment]
How did you target Firefox to remove the the styling? Couldn't you just remove the width that way?

**Comment by laurendorman** [comment]
I removed the styling simply by not including `-moz-appearance`, where I included `-webkit-appearance: none;` and `appearance: none;` otherwise.

**Comment by kaseybon** [comment]
hmmm

**Comment by kaseybon** [comment]
This is only an issue on Mac, the radio buttons look great in FF on Windows

**Comment by laurendorman** [comment]
@kaseybon, now that's really interesting.

**Comment by cromwellryan** [comment]
@kaseybon is this still a thing?

**Comment by kaseybon** [comment]
Nope. They aren't styled like the other radio buttons but they aren't squashed.
