### ISSUE TITLE
IE 8: About & submit page headings

### ISSUE THREAD

**Issue by kaseybon** [sparkbox/apprentice-at#190]
The white background is collapsed below the first header
![screen shot 2015-06-16 at 9 25 17 am](https://cloud.githubusercontent.com/assets/2486846/8183974/a4fe42d4-1409-11e5-88e8-f8cbbf089d58.png)

**Comment by danrosenthal** [comment]
This wasn't happening a few days ago. What changed between now and then?

**Comment by kaseybon** [comment]
I figured it out. It's a z-index issue in IE8. That is the background image for the psuedo element in the header sitting on top of the white background. The background used to be a png so you didn't notice as much but now it's a jpg.
