### ISSUE TITLE
iPad: Space below homepage SVG header

### ISSUE THREAD

**Issue by laurendorman** [sparkbox/apprentice-at#196]
![image](https://cloud.githubusercontent.com/assets/6477234/8185869/d0c04b82-1414-11e5-9ac5-6669f4431ffe.jpg)
![image 1](https://cloud.githubusercontent.com/assets/6477234/8185911/03ec9696-1415-11e5-8201-170c9577528a.jpg)
There is a large blank space below the header, in the second screen shot, you can see where the scroll bar is positioned on the page before you actually see content on the homepage.

**Comment by kaseybon** [comment]
This is a reoccuring issue on a lot of devices. I'll try and fix it when I optimize the svg
