### ISSUE TITLE
iPad: Duration text misaligned, input drop shadows remain in Safari

### ISSUE THREAD

**Issue by laurendorman** [sparkbox/apprentice-at#197]
![image 2](https://cloud.githubusercontent.com/assets/6477234/8185991/80490152-1415-11e5-8986-7effe19ac96c.jpg)

**Comment by kaseybon** [comment]
@laurendorman I found the fix to this when working on another bug :) We just needed to add input[type='url'] and textarea to the list of items getting -webkit-appearance: none. I'll include it in my upcoming pull request.

**Comment by laurendorman** [comment]
@kaseybon, awesome! That works.
