### ISSUE TITLE
Add IDs to each apprenticeship to make them linkable

### ISSUE THREAD

**Issue by danrosenthal** [sparkbox/apprentice-at#234]

**Comment by kaseybon** [comment]
I used @bryanbraun's [AnchorJS](http://bryanbraun.github.io/anchorjs/) and it looks pretty sweet!

![screen shot 2015-08-07 at 11 13 38 am](https://cloud.githubusercontent.com/assets/2486846/9139146/47892e50-3cf6-11e5-902a-0cb45b818fcc.png)

I just need to device test this and then it will be ready for review.
