### ISSUE TITLE
Switch hosting to Netlify

### ISSUE THREAD

**Issue by nrambeck** [sparkbox/apprentice-at#279]
Use Netlify for hosting, taking advantage of their forms processing tool.

Try to get PR deploys working as well.

**Comment by bryanbraun** [comment]
This was completed as part of the new-tech hack-morning (see #280).

![apprentice_at](https://user-images.githubusercontent.com/1256329/48639596-04d76980-e9a2-11e8-8cf8-4a230a3cf911.png)
