### ISSUE TITLE
fix: headings so the home page only has one h1

### ISSUE THREAD

**Issue by corinneling** [sparkbox/apprentice-at#285]
Currently the home page of apprentice.at has multiple H1 headings as seen by the screenshot below:

<img width="904" alt="Screen Shot 2020-10-05 at 7 22 42 PM" alt="result of Wave audit - details section - showing the page has 11 H1s" src="https://user-images.githubusercontent.com/31801723/95141853-39906d80-0740-11eb-8373-16ab66e85df4.png">

While it is okay to add H1s to article tags, we believe that updating most of them to H2s will make this page easier to navigate, and make the structure of the page more apparent when using a screen reader.

To fix this update the h1 in the _apprenticeship.hbs file located [here](https://github.com/sparkbox/apprentice-at/blob/master/source/templates/partials/_apprenticeship.hbs) to an h2

**Comment by erin-sparkbox** [comment]
Can I take this one?

**Comment by corinneling** [comment]
yes!

**Comment by bryanbraun** [comment]
Closing this, because it was merged in https://github.com/sparkbox/apprentice-at/pull/298. Thanks @erin-sparkbox!
