### ISSUE TITLE
fix: update nav to use semantic html

### ISSUE THREAD

**Issue by corinneling** [sparkbox/apprentice-at#287]
Currently the navigation for apprentice.at is wrapped in a `<section>` tag.

Update the [_action.hbs file](https://github.com/sparkbox/apprentice-at/blob/master/source/templates/partials/_action.hbs) so the `<section>` tag is a [`<nav>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav) tag so that screen reader users can be notified that that the links within the `<nav>` are part of the website's navigation. For more information on semantic html check out [this article](https://www.internetingishard.com/html-and-css/semantic-html/)

See screenshot below of the current links to other pages on the apprentice.at site:
![Apprentice_at-nav](https://user-images.githubusercontent.com/31801723/95467174-27cee600-094b-11eb-8487-a270a80dc484.png)

**Comment by erin-sparkbox** [comment]
I can take this one!
