### ISSUE TITLE
fix: heading skipped on about page

### ISSUE THREAD

**Issue by corinneling** [sparkbox/apprentice-at#288]
On the [about](https://apprentice.at/about/) and [submit](https://apprentice.at/submit/) pages there is the following heading structure:

```
  <h1>First Heading</h1>
  <h1>Second Heading</h1>
```

Update the second h1 to be an h2 by editing the [_content__header--inside.hbs file](https://github.com/sparkbox/apprentice-at/blob/master/source/templates/partials/_content__header--inside.hbs). Also update the `<header>` to a `<div>` since its unnecessary semantic html

This work should include adding an h1 to wrap around the svg header on the home page. This can be done by editing the [_header.hbs file](https://github.com/sparkbox/apprentice-at/blob/master/source/templates/partials/_header.hbs). Wrap the `<object>` tag with an `<h1>` tag, and give the h1 and aria-label with the value "Apprenticeships".

See screenshots of the current heading structure of home, about, and submit pages:
![Apprentice_at-home-heading](https://user-images.githubusercontent.com/31801723/95468070-27831a80-094c-11eb-9dff-8ac3eb67ea41.png)
![Apprentice_at-about-headings](https://user-images.githubusercontent.com/31801723/95468088-2b16a180-094c-11eb-9def-a42d4e1355fe.png)
![Apprentice_at-submit-headings](https://user-images.githubusercontent.com/31801723/95468107-2e119200-094c-11eb-8f40-6abd8b6eaf78.png)

**Comment by ProxN** [comment]
hi,
here my [pr](https://github.com/sparkbox/apprentice-at/pull/307)
