### ISSUE TITLE
fix: footer link hover states

### ISSUE THREAD

**Issue by corinneling** [sparkbox/apprentice-at#292]
Add hover state to Sparkbox logo link and report link in the footer. For more information check out WebAIM's article on [WCAG 2.0 and Link Colors](https://webaim.org/blog/wcag-2-0-and-link-colors/)

Report Link:
Update the styles of the report link in the [_report.scss file](https://github.com/sparkbox/apprentice-at/blob/master/source/scss/modules/_report.scss). Currently the color changes on hover, but we need something that's a little more distinguishable all users can tell it is a link. Either add an underline, a background color change, or a border on hover.

Sparkbox Logo Link:
Update the styles of the `footer__logo` in the [_footer.scss file](https://github.com/sparkbox/apprentice-at/blob/master/source/scss/modules/_footer.scss#L12). You may have to use the following css selector: `.sparkbox-logo:hover .footer__logo { }`. Either add an underline, a background color change, or a border on hover.

See screenshot of these links at the bottom of each page:
![Apprentice_at-footer-links](https://user-images.githubusercontent.com/31801723/95471411-eb51b900-094f-11eb-9856-cb4bd23e2047.png)

**Comment by ProxN** [comment]
Hi,
Here my [pr](https://github.com/sparkbox/apprentice-at/pull/303)
